services:
  - type: web
    name: pettshop-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://pettshop-ecommerce.onrender.com 